config/routes.rb
Rails.application.routes.draw do
  resources :safetypins
  resources :pins
  devise_for :users
  root "safetypins#index"
  get "resources" => "pages#resources"
  get "checkin" => "pages#checkin"
  get "youvecheckedin" => "pages#youvecheckedin"

end

app/models/pin.rb
class Pin < ActiveRecord::Base
	belongs_to :user
	has_attached_file :image, :styles => { :medium => "300x300", :thumb => "100x100"}

	geocoded_by :longitude
    after_validation :geocode

end

app/models/recipient.rb
class Recipient < ActiveRecord::Base
	belongs_to :user
	has_many :users
	has_one :phone
end

app/models/safetypin.rb
class Safetypin < ActiveRecord::Base

	belongs_to :user
	
	geocoded_by :address
	after_validation :geocode
	
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   has_many :pins
   has_one :recipient
   has_one :phone
   has_many :safetypins
   
   validates :contactname, presence: true
   validates :contactnumber, presence: true
   validates :contactnumber, :phone_number => {:ten_digits => true, :message => "Invalid phone number. Please enter a 10-digit number."}

  

   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
  	devise_parameter_sanitizer.for(:sign_up) << :contactname
  	devise_parameter_sanitizer.for(:account_update) << :contactname
  	devise_parameter_sanitizer.for(:sign_up) << :contactnumber
  	devise_parameter_sanitizer.for(:account_update) << :contactnumber
  end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  def resources
  end
  def pins
  end
  def checkin
  end
  def youvecheckedin
  end
  def home_map
  end
  def safetypins
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:add, :edit, :destroy]
  before_action :authenticate_user!, only: [:new]

  def index # list of pins, read all
    @pins = Pin.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 3)
    @hash = Gmaps4rails.build_markers(@pins) do |pin, marker|
    marker.lat pin.latitude
    marker.lng pin.longitude
    end
  end

  def show # read
  end

  def new # opens new page to create pin
    @pin = current_user.pins.build
  end

  def edit # update
  end

  def create # actually creates pin
    @pin = current_user.pins.build(pin_params)

      if @pin.save
        redirect_to @pin, notice: 'Pin was successfully created.'
      else
        render :new
      end
  end

  def update
      if @pin.update(pin_params)
        redirect_to @pin, notice: 'Pin was successfully updated.' 
      else
        render :edit 
      end
  end

  def destroy
    @pin.destroy
      redirect_to pins_url, notice: 'Pin was successfully deleted.'
  end

  private
    def set_pin
      @pin = Pin.find(params[:id])
    end

    def correct_user
      @pin = current_user.pins.find_by(id: params[:id])
      redirect_to pins_path, notice: "Sorry, you are not authorized to edit this pin." if @pin.nil?
    end

    def pin_params
      params.require(:pin).permit(:description, :image)
    end
end

app/controllers/safetypins_controller.rb
class SafetypinsController < ApplicationController
  before_action :set_safetypin, only: [:show, :edit, :update, :destroy]

  # GET /safetypins
  # GET /safetypins.json
  def index
    @safetypins = Safetypin.all
    @hash = Gmaps4rails.build_markers(@safetypins) do |safetypin, marker|
    marker.lat safetypin.latitude
    marker.lng safetypin.longitude
    marker.infowindow safetypin.description

  end
  end

  # GET /safetypins/1
  # GET /safetypins/1.json
  def show
  end

  # GET /safetypins/new
  def new
    @safetypin = Safetypin.new
  end

  # GET /safetypins/1/edit
  def edit
  end

  # POST /safetypins
  # POST /safetypins.json
  def create
    @safetypin = Safetypin.new(safetypin_params)

    respond_to do |format|
      if @safetypin.save
        format.html { redirect_to @safetypin, notice: 'Safetypin was successfully created.' }
        format.json { render :show, status: :created, location: @safetypin }
      else
        format.html { render :new }
        format.json { render json: @safetypin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /safetypins/1
  # PATCH/PUT /safetypins/1.json
  def update
    respond_to do |format|
      if @safetypin.update(safetypin_params)
        format.html { redirect_to @safetypin, notice: 'Safetypin was successfully updated.' }
        format.json { render :show, status: :ok, location: @safetypin }
      else
        format.html { render :edit }
        format.json { render json: @safetypin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /safetypins/1
  # DELETE /safetypins/1.json
  def destroy
    @safetypin.destroy
    respond_to do |format|
      format.html { redirect_to safetypins_url, notice: 'Safetypin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_safetypin
      @safetypin = Safetypin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def safetypin_params
      params.require(:safetypin).permit(:latitude, :longitude, :address, :description)
    end
end

app/controllers/users/confirmations_controller.rb
class users::confirmationsController < Devise::confirmationsController

	@users = User.all
@hash = Gmaps4rails.build_markers(@users) do |user, marker|
  marker.lat user.latitude
  marker.lng user.longitude
end
  # def new
  #   super
  # end

  # def create
  #   super
  # end
end

app/controllers/users/passwords_controller.rb
class users::passwordsController < Devise::passwordsController
  # def new
  #   super
  # end

  # def create
  #   super
  # end
end

app/controllers/users/registrations_controller.rb
class users::registrationsController < Devise::registrationsController
  # def new
  #   super
  # end

  # def create
  #   super
  # end

  

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # def new
  #   super
  # end

  # def create
  #   super
  # end
end

app/controllers/users/unlocks_controller.rb
class users::unlocksController < Devise::unlocksController
  # def new
  #   super
  # end

  # def create
  #   super
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper

	require 'twilio-ruby'
 
account_sid = "ACc5f41492a98302b14af7c8537a10ad5b"
auth_token = "86d6f21f4ff412ad0f9bd4615b98c4a5"
client = Twilio::REST::Client.new account_sid, auth_token
 
from = "+19402224451" # Your Twilio number
 
contact = {
"+19403950595" => "Ariel",

}
contact.each do |key, value|
  client.account.messages.create(
    :from => from,
    :to => key,
    :body => "Hey #{value}, Monkey party at 6PM. Bring Bananas!"
  )
  puts "Sent message to #{value}"
end

end

app/helpers/pages_helper.rb
module PagesHelper


end

app/helpers/pins_helper.rb
module PinsHelper
end

app/helpers/safetypins_helper.rb
module SafetypinsHelper

	def send_text_message
    number_to_send_to = user.contactnumber
    twilio_sid = ENV["ACc5f41492a98302b14af7c8537a10ad5b"]
    twilio_token = ENV["T86d6f21f4ff412ad0f9bd4615b98c4a5"]
    twilio_phone_number = ENV["+19402224451"]
    @twilio_client = Twilio::REST::Client.new twilio_sid, twilio_token
    @twilio_client.account.sms.messages.create(
      :from => "+19402224451",
      :to => number_to_send_to,
      :body => message
    )
 end
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "UNT Safe", root_path, class:"navbar-brand" %>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav navbar-right"> 
      <li><%= link_to "Resources", resources_path %></li> 
      <% if user_signed_in? %>
        <li>
          <%= link_to checkin_path do %>
            Check In
          <% end %>
          
        </li>
        <li>
          <%= link_to destroy_user_session_path, method: :delete do %>
            Log Out
          <% end %>
        </li>
        <li><%= link_to "Settings", edit_user_registration_path %></li>
      <% else %>
        <li><%= link_to "Log in", new_user_session_path %></li>
      <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UNTsafetyApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

<%= render 'layouts/header' %>
<div class="container">

<% flash.each do |name, msg| %>
	<%= content_tag(:div, msg, class:"alert alert-#{name}") %>
<% end %>

   <%= yield %>
</div>

</body>
</html>

app/views/pages/About.html.erb
<h1>About</h1>
<p>Yaaaay</p>

app/views/pages/_home.html.erb
<div class="jumbotron">
	<h1>Welcome to UNT Safe!</h1>
		<div class="center">
			<%= link_to "Log In", new_user_session_path, class: "btn btn-default btn-lg" %>
			<%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
		</div>
</div>

app/views/pages/checkin.html.erb
<h1>Check in with your contact.</h1>

<p>Before you travel at unsafe times, let your contact know where you're going so they can keep tabs on you for safety!</p>
<p>Click "Check in" and we will send a text to your contact letting them know where you are. When you get to your destination, click "I've arrived" to let them know you're safe.</p>

<hr>

		<div class="center">
			
			<!-- Button trigger modal -->
			<button type="button" class="btn btn-success btn-lg btn-block" data-toggle="modal" data-target="#myModal">
			  Check in
			</button>

			<!-- Modal -->
			<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
			  <div class="modal-dialog" role="document">
			    <div class="modal-content">
			      <div class="modal-header">
			        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
			        <h4 class="modal-title" id="myModalLabel">Check in with your contact.</h4>
			      </div>
			      <div class="modal-body">
			     	FORM:
			     	Contact: [autofill]
			     	ETA: [select]
			     	Message: [autofill]
					
			      </div>
			      <div class="modal-footer">
			        <%= link_to "Send SMS", :method => :send_text_message, class: "btn btn-success btn-lg btn-block" %>

			        <br>
			        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
			      </div>
			    </div>
			  </div>
			</div>

		</div>
		<br>
		<div class="center">
			<%= link_to "Update your contact", edit_user_registration_path, class: "btn btn-default btn-lg btn-block" %>
		</div>

app/views/pages/home.html.erb
<div class="jumbotron">
	<h1>Welcome to UNT Safe!</h1>
		
	<% if user_signed_in? %>
	This is the UNT Safety App. 
	<% else %>
		<p>Please login or create an account to continue.</p>
		<%= link_to "Log In", new_user_session_path, class: "btn btn-default btn-lg" %>
		<%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
	<% end %>
</div>

app/views/pages/home_map.html.erb
<script src="//maps.google.com/maps/api/js?v=3.18&sensor=false&client=&key=&libraries=geometry&language=&hl=&region="></script> 
<script src="//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/infobox/1.1.9/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->

<script>
    markers = handler.addMarkers(<%=raw @hash.to_json %>);
</script>

<%= render 'pages/home' unless user_signed_in? %>

<% if user_signed_in? %>

<h1>Safety Map</h1>
<p>Create or view pins on the map below that mark safety issues and incidences on campus.</p>

<hr>



<br>

<% end %>

<div class="center">
  <%= link_to "View All Pins", pins_path, class: "btn btn-default" %>
  <%= link_to "New Pin", new_pin_path, class: "btn btn-success" %>
</div>
<br>

app/views/pages/youvecheckedin.html.erb
<h1>You've checked in!</h1>
<p>Let your contact know when you've arrived safely at your destination or need help.</p>
<p>Click the red button to call the police during an emergency.</p>

<hr>

<div class="center">
			<%= link_to "I've arrived.", root_path, class: "btn btn-success btn-lg btn-block" %>
		</div>
		<br>
		<div class="center">
			<%= link_to "Call your contact", youvecheckedin_path, class: "btn btn-warning btn-lg btn-block" %>
		</div>
		<br>
		<div class="center">
			<%= link_to "EMERGENCY: Dial 911.", youvecheckedin_path, class: "btn btn-danger btn-lg btn-block" %>
		</div>
		<br>
		<div class="center">
			<%= link_to "Send a report.", resources_path, class: "btn btn-default btn-lg btn-block" %>
		</div>

app/views/pins/edit.html.erb
<h1>Editing Pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<%= render 'pages/home' unless user_signed_in? %>

<div style='width: full;'>
  <div id="geolocation" style='width: full; height: 500px;'></div>
</div>

<script type="text/javascript">
 var handler = Gmaps.build('Google');
handler.buildMap({ internal: {id: 'geolocation'} }, function(){
  if(navigator.geolocation)
    navigator.geolocation.getCurrentPosition(displayOnMap);
});

function displayOnMap(position){
  var marker = handler.addMarker({
    lat: position.coords.latitude,
    lng: position.coords.longitude,
  });
  handler.map.centerOn(marker);
};

  var markers = handler.addMarkers(<%=raw @hash.to_json %>);
</script>

<div style='width: full;'>
  <div id="map" style='width: full; height: 500px;'></div>
</div>

<script type="text/javascript">
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
    markers = handler.addMarkers(<%=raw @hash.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
  });
</script>


<div id="pins" class="transitions-enabled">

  <% @pins.each do |pin| %>

    <div class="box panel panel-default">
              <%= link_to image_tag(pin.image.url(:medium)), pin %>
      <div class="panel-body">
        <%= pin.description %>
        <br>
        <strong><%= pin.user.email if pin.user %></strong>
      
        <% if pin.user == current_user %>
          <div class="actions">
            <%= link_to 'Edit', edit_pin_path(pin) %>
            <%= link_to 'Delete', pin, method: :delete, data: { confirm: 'Are you sure you would like to delete your pin?' } %>
          </div>
        <% end %>
      </div>
    </div>

  <% end %>

</div>

<div class="center">
  <%= link_to "New Pin", new_pin_path, class: "btn btn-default" %>
</div>

<div class="center">
  <%= will_paginate @pins, renderer: BootstrapPagination::Rails  %>
</div>

app/views/pins/index.html_BACKUP_49888.erb
<%= render 'pages/home' unless user_signed_in? %>

<div style='width: full;'>
  <div id="geolocation" style='width: full; height: 500px;'></div>
</div>

<script type="text/javascript">
 var handler = Gmaps.build('Google');
handler.buildMap({ internal: {id: 'geolocation'} }, function(){
  if(navigator.geolocation)
    navigator.geolocation.getCurrentPosition(displayOnMap);
});

function displayOnMap(position){
  var marker = handler.addMarker({
    lat: position.coords.latitude,
    lng: position.coords.longitude,
  });
  handler.map.centerOn(marker);
};

  var markers = handler.addMarkers(<%=raw @hash.to_json %>);
<<<<<<< HEAD
</script>

<div style='width: full;'>
  <div id="map" style='width: full; height: 500px;'></div>
</div>

<script type="text/javascript">
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
    markers = handler.addMarkers(<%=raw @hash.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
  });
=======
>>>>>>> parent of ef9b150... MAP WORKING AT LAST
</script>


<div id="pins" class="transitions-enabled">

  <% @pins.each do |pin| %>

    <div class="box panel panel-default">
              <%= link_to image_tag(pin.image.url(:medium)), pin %>
      <div class="panel-body">
        <%= pin.description %>
        <br>
        <strong><%= pin.user.email if pin.user %></strong>
      
        <% if pin.user == current_user %>
          <div class="actions">
            <%= link_to 'Edit', edit_pin_path(pin) %>
            <%= link_to 'Delete', pin, method: :delete, data: { confirm: 'Are you sure you would like to delete your pin?' } %>
          </div>
        <% end %>
      </div>
    </div>

  <% end %>

</div>

<div class="center">
  <%= link_to "New Pin", new_pin_path, class: "btn btn-default" %>
</div>

<div class="center">
  <%= will_paginate @pins, renderer: BootstrapPagination::Rails  %>
</div>

app/views/pins/index.html_BASE_49888.erb
<%= render 'pages/home' unless user_signed_in? %>

<div style='width: full;'>
  <div id="geolocation" style='width: full; height: 500px;'></div>
</div>

<script type="text/javascript">
     var handler = Gmaps.build('Google');
    handler.buildMap({ internal: {id: 'geolocation'} }, function(){
      if(navigator.geolocation)
        navigator.geolocation.getCurrentPosition(displayOnMap);
    markers = handler.addMarkers(<%=raw @hash.to_json %>);
    handler.bounds.extendWith(markers);
    });

    function displayOnMap(position){
      var marker = handler.addMarker({
        lat: position.coords.latitude,
        lng: position.coords.longitude,
      });
      handler.map.centerOn(marker);
    };

      var markers = handler.addMarkers(<%=raw @hash.to_json %>);
</script>


<div id="pins" class="transitions-enabled">

  <% @pins.each do |pin| %>

    <div class="box panel panel-default">
              <%= link_to image_tag(pin.image.url(:medium)), pin %>
      <div class="panel-body">
        <%= pin.description %>
        <br>
        <strong><%= pin.user.email if pin.user %></strong>
      
        <% if pin.user == current_user %>
          <div class="actions">
            <%= link_to 'Edit', edit_pin_path(pin) %>
            <%= link_to 'Delete', pin, method: :delete, data: { confirm: 'Are you sure you would like to delete your pin?' } %>
          </div>
        <% end %>
      </div>
    </div>

  <% end %>

</div>

<div class="center">
  <%= link_to "New Pin", new_pin_path, class: "btn btn-default" %>
</div>

<div class="center">
  <%= will_paginate @pins, renderer: BootstrapPagination::Rails  %>
</div>

app/views/pins/index.html_LOCAL_49888.erb
<%= render 'pages/home' unless user_signed_in? %>

<div style='width: full;'>
  <div id="geolocation" style='width: full; height: 500px;'></div>
</div>

<script type="text/javascript">
 var handler = Gmaps.build('Google');
handler.buildMap({ internal: {id: 'geolocation'} }, function(){
  if(navigator.geolocation)
    navigator.geolocation.getCurrentPosition(displayOnMap);
});

function displayOnMap(position){
  var marker = handler.addMarker({
    lat: position.coords.latitude,
    lng: position.coords.longitude,
  });
  handler.map.centerOn(marker);
};

  var markers = handler.addMarkers(<%=raw @hash.to_json %>);
</script>

<div style='width: full;'>
  <div id="map" style='width: full; height: 500px;'></div>
</div>

<script type="text/javascript">
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
    markers = handler.addMarkers(<%=raw @hash.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
  });
</script>


<div id="pins" class="transitions-enabled">

  <% @pins.each do |pin| %>

    <div class="box panel panel-default">
              <%= link_to image_tag(pin.image.url(:medium)), pin %>
      <div class="panel-body">
        <%= pin.description %>
        <br>
        <strong><%= pin.user.email if pin.user %></strong>
      
        <% if pin.user == current_user %>
          <div class="actions">
            <%= link_to 'Edit', edit_pin_path(pin) %>
            <%= link_to 'Delete', pin, method: :delete, data: { confirm: 'Are you sure you would like to delete your pin?' } %>
          </div>
        <% end %>
      </div>
    </div>

  <% end %>

</div>

<div class="center">
  <%= link_to "New Pin", new_pin_path, class: "btn btn-default" %>
</div>

<div class="center">
  <%= will_paginate @pins, renderer: BootstrapPagination::Rails  %>
</div>

app/views/pins/index.html_REMOTE_49888.erb
<%= render 'pages/home' unless user_signed_in? %>

<div style='width: full;'>
  <div id="geolocation" style='width: full; height: 500px;'></div>
</div>

<script type="text/javascript">
 var handler = Gmaps.build('Google');
handler.buildMap({ internal: {id: 'geolocation'} }, function(){
  if(navigator.geolocation)
    navigator.geolocation.getCurrentPosition(displayOnMap);
});

function displayOnMap(position){
  var marker = handler.addMarker({
    lat: position.coords.latitude,
    lng: position.coords.longitude,
  });
  handler.map.centerOn(marker);
};

  var markers = handler.addMarkers(<%=raw @hash.to_json %>);
</script>


<div id="pins" class="transitions-enabled">

  <% @pins.each do |pin| %>

    <div class="box panel panel-default">
              <%= link_to image_tag(pin.image.url(:medium)), pin %>
      <div class="panel-body">
        <%= pin.description %>
        <br>
        <strong><%= pin.user.email if pin.user %></strong>
      
        <% if pin.user == current_user %>
          <div class="actions">
            <%= link_to 'Edit', edit_pin_path(pin) %>
            <%= link_to 'Delete', pin, method: :delete, data: { confirm: 'Are you sure you would like to delete your pin?' } %>
          </div>
        <% end %>
      </div>
    </div>

  <% end %>

</div>

<div class="center">
  <%= link_to "New Pin", new_pin_path, class: "btn btn-default" %>
</div>

<div class="center">
  <%= will_paginate @pins, renderer: BootstrapPagination::Rails  %>
</div>

app/views/pins/new.html.erb
<h1>New Pin</h1>

<%= render 'form' %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Back', pins_path %>

<div class="row">
	<div class="col-md-offset-2 col-md-8"
		<div class="panel panel-default">
			<div class="panel-heading center">
				<%= image_tag @pin.image.url(:medium) %>
			</div>
			<div class="panel-body">
				<p><%= @pin.description %></p>
				<p><strong><%= @pin.user.email if @pin.user %></strong></p>
				<% if @pin.user == current_user %>
					<%= link_to 'Edit', edit_pin_path(@pin) %> | 
					<%= link_to 'Delete', @pin, method: :delete, data: { confirm: 'Are you sure you would like to delete your pin?' } %>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/safetypins/edit.html.erb
<h1>Editing Safetypin</h1>

<%= render 'form' %>

<%= link_to 'Show', @safetypin %> |
<%= link_to 'Back', safetypins_path %>

app/views/safetypins/index.html.erb
<script src="//maps.google.com/maps/api/js?v=3.18&sensor=false&client=&key=&libraries=geometry&language=&hl=&region="></script> 
<script src="//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/infobox/1.1.9/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->

<div style='width: full;'>
  <div id="map" style='width: full; height: 500px;'></div>
</div>

<script type="text/javascript">
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
    markers = handler.addMarkers(<%=raw @hash.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
  });
</script>

<br>

<div class="center">
  <%= link_to "New Pin", new_safetypin_path, class: "btn btn-success btn-lg btn-block" %>
</div>

<br>

<h2>Browse Safety Pins</h2>

<table class="table table-hover">
  <thead>
    <tr>

      <th>Address</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @safetypins.each do |safetypin| %>
      <tr>

        <td><%= safetypin.address %></td>
        <td><%= safetypin.description %></td>
        <td><%= link_to 'View', safetypin %></td>
        <td><%= link_to 'Edit', edit_safetypin_path(safetypin) %></td>
        <td><%= link_to 'Delete', safetypin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<br>

app/views/safetypins/new.html.erb
<h1>New Safety Pin</h1>

<%= render 'form' %>

<%= link_to 'Back', safetypins_path %>

app/views/safetypins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Latitude:</strong>
  <%= @safetypin.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @safetypin.longitude %>
</p>

<p>
  <strong>Address:</strong>
  <%= @safetypin.address %>
</p>

<p>
  <strong>Description:</strong>
  <%= @safetypin.description %>
</p>

<%= link_to 'Edit', edit_safetypin_path(@safetypin) %> |
<%= link_to 'Back', safetypins_path %>